---
- hosts: server
  become: yes
  roles:
    - WebServer
  vars:
    db_host: db
    db_name: 'your_db_name'
    db_user: 'your_db_user'
    db_pass: 'your_db_password'

- hosts: db
  become: yes
  roles:
    - DBServer
