---
- name: Встановити необхідні пакети
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
      - nodejs
      - npm
    state: present

- name: Встановити Composer глобально
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
- name: Запустити Composer installer
    command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer

- name: Клонувати репозиторій додатку
  git:
    repo: 'https://github.com/Practical-DevOps/app-for-devops.git'
    dest: '/var/www/html/app-for-devops'
    clone: yes

- name: Встановити залежності Laravel через Composer
  command:
    cmd: composer install
    chdir: /var/www/html/app-for-devops

- name: Запустити php artisan key:generate для Laravel
  command:
    cmd: php artisan key:generate
    chdir: /var/www/html/app-for-devops

- name: Запустити php artisan migrate для Laravel
  command:
    cmd: php artisan migrate
    chdir: /var/www/html/app-for-devops
  environment:
    DB_CONNECTION: mysql
    DB_HOST: "{{ db_host }}"
    DB_PORT: 3306
    DB_DATABASE: "{{ db_name }}"
    DB_USERNAME: "{{ db_user }}"
    DB_PASSWORD: "{{ db_pass }}"

- name: Встановити фронтенд залежності через NPM
  command:
    cmd: npm install
    chdir: /var/www/html/app-for-devops

- name: Збірка активів додатку через NPM
  command:
    cmd: npm run build
    chdir: /var/www/html/app-for-devops

- name: Налаштувати .env файл для Laravel
  template:
    src: db_config.j2
    dest: /var/www/html/app-for-devops/.env
