---
- name: Встановити MariaDB сервер
  apt:
    name:
      - mariadb-server
    state: present

- name: Надати доступ з віддалених машин
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    line: "bind-address = 0.0.0.0"
    regexp: '^bind-address'
    state: present

- name: Перезапустити MariaDB
  service:
    name: mariadb
    state: restarted
